name: Build Fusion Boxes

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRODUCT_VERSION: "latest"
  FUSION_INSTALLER_FILENAME: "VMware-Fusion-13.6.2-24409261_universal.dmg"
  GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}
  GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}

jobs:
  # for arm64 builds
  fusion-aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download fusion installer
        run: |
          wget -q -O ${{ env.FUSION_INSTALLER_FILENAME }} "https://www.googleapis.com/drive/v3/files/${{ env.GDRIVE_FILE_ID }}?alt=media&key=${{ env.GDRIVE_API_KEY }}"
          md5 ${{ env.FUSION_INSTALLER_FILENAME }}

      - name: Mount and install
        run: |
          hdiutil attach ${{ env.FUSION_INSTALLER_FILENAME }}
          sudo cp -R /Volumes/VMware\ Fusion/VMware\ Fusion.app /Applications
          echo "Fusion installed."

      - name: Clean up
        run: |
          hdiutil unmount /Volumes/VMware\ Fusion/
          rm -f ${{ env.FUSION_INSTALLER_FILENAME }}

      # https://github.com/hashicorp/setup-packer
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      # For debug
      - name: Test buildings with packer
        env:
          VAGRANT_HCP_CLIENT_ID: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
          VAGRANT_HCP_CLIENT_SECRET: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd alpine/
          packer init .
          echo ""
          echo ""
          packer validate .
          echo ""
          echo ""
          PACKER_LOG=1 packer build -only vmware-iso.alpine_arm64 .

  # for amd64 builds
  fusion-x86-64:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download fusion installer
        run: |
          wget -q -O ${{ env.FUSION_INSTALLER_FILENAME }} "https://www.googleapis.com/drive/v3/files/${{ env.GDRIVE_FILE_ID }}?alt=media&key=${{ env.GDRIVE_API_KEY }}"
          md5 ${{ env.FUSION_INSTALLER_FILENAME }}

      - name: Mount and install
        run: |
          hdiutil attach ${{ env.FUSION_INSTALLER_FILENAME }}
          sudo cp -R /Volumes/VMware\ Fusion/VMware\ Fusion.app /Applications
          echo "Fusion installed."

      - name: Clean up
        run: |
          hdiutil unmount /Volumes/VMware\ Fusion/
          rm -f ${{ env.FUSION_INSTALLER_FILENAME }}

      # https://github.com/hashicorp/setup-packer
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      # For debug
      - name: Test buildings with packer
        env:
          VAGRANT_HCP_CLIENT_ID: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
          VAGRANT_HCP_CLIENT_SECRET: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd alpine/
          packer init .
          echo ""
          echo ""
          packer validate .
          echo ""
          echo ""
          PACKER_LOG=1 packer build -only vmware-iso.alpine_amd64 .
