# branches:
#   only:
#     - main

branches:
  except: /^(main).*$/

language: generic

env:
  global:
    - secure: "ChkCosBLQ4G9qIO4W3v5IlhFI1eaxnaAkhLt4ujE3431gHhqPdto17E2njZ/pY5UzVpBL4gXJlSbqwDJR7mGzpSPRKo+UOAQ+LlDQ3DkAwEpLcYLz5YELHXdhnD3a80R6RhlTXW0mMTqaPtScbG9njrz/4TnSJqmEiYDxwzvq/E2LNVEEHl2Xkhw4DA5tr2fibJu6puUtNlkzc5AHr0AW3TyThPX34f4DujKbUnAnScmToHPlHtegfWUj7NdvNVgBjv1so+DZeo8UKqmkidHzoAPN+yCIZKdHc+tXdt01CopRm1XnJVDYzcXW3ZEOp79vjjDVX4E03yPfsfHaEAqfy4R2NX75Tdm4heOmfgnIyyRswXBRlvsG4Vrz2ifvmUxSqmMlMk8JAcuK1ShpNtoxJSmgxKRjm4+MzW5mFMqdGz2ZXMTJZFmibJdYfdu70jDpWd8lsiCC2rUPm5gqQGvi+K91UstyOyA4M3IIFK2On7+8pNShlT4aS0TNkJ+Sw/YMfwe48YFshiTVjlpgmO9pNMegX9fAXfbZsyLrzd3dVHk1c74GGfpwumyDmgFyoEzpfzvtanboFPSQygk9D7HiSgzOTMyjOW/yYWgRIi75VlqhlXMJ/rggYbSXtYJA6yUBwumWg9/7XEE54JHL0seNGMkdCMHeaM/cjBhELCcXfI="
    - secure: "edV3SuvqqfP69iLaMhNF9u+yeL5F6TiWauTNcV2y6Zym/6HdJtgmfoha21J+OfUiLNBSwb8skjbhJ/5wVkDC+m+C5wajZyf/4AAKbJEQ6JdI59dyfDGAb18DzFJxaCQ3N6ro8NNEcFybcRSrhRoC3u5q54/XTxsEz8x+e/eNsSdw16OLXBo3kZB6jtdRWSQicfRYy1EdQnLA2hR9he2W6P+Yz2YRRgY0N0wVzzVfJEBdl9+lBLJ226Otk1/JJj+nGj2UX68e5s7ATJIRa7xHl2vCjWNp46wZBr8O4MBbIPRoS5/UJ5UalFoVwTgj8qAfmOjB2sOZDs78Q1gVuuIDlI6GZXPHzkCB+RPk76dYXaXobSQGaD/7AWcKtrwysGYodtOJy83OgIUUuIzDSEc8wk906mf0gLFPvorIPtWZO4je+LjdxzryA3NkrcVtPgiB2AiX3kjGt+P+pB7EXsYbzrNdsv2rt0x71pX1s8/yzEU1YHnjvEwmu68T1uROvnxzsJlo2rWC+IcG1/pyCbn0hLdCBg7fIgBUb74J/5lGfd0J4VLV7ZQmdPUiUM6uwsjyCwOZeYfcvV3IOcpAob/TQ3KYKRWamWs2sOvCmPxMIes8Y3dHl7r5eAjfc9Tvab/XHPKQspRdB/0PtZ/OEHAVwBlf+QdIA1SRXgBW+ONJXAM="
    - secure: "BjzbyvdhZ70WBU+qwjYUvqTN6NJ+o8+SoMkqL4MuxGoIiXf4gnwDUSiBzP3ch2GgKP31dDPNQXwSCzECI9l4bc0JlQX0EeNMIJnRFTsbzEzjaPcif8XOH3FQclTttpnqypk9+n2vZVDvdb0cLP/gp3QJfVLJu7icaxvSazYax2gxpEhrv70UJH1PQhr31d6cN/fH0BIbVNRyayEJ1MsqRP2BEjM0yVMprb6ydEEKbP8EblH3JxC/gbMftlf0CHnhE7O+QCPpjqbU1l8ZCHj4Ul1L/fOBtVVZwZlGqu908owgHTfRAoUkvsNCNlV1n6nzB0whDX8uuUnX2tANQy12FgfmT4ituIvVA5GJ/F6Hx4hcL2rcyZqqFsktdpVF3z8oZDN9smwd2JyBWIW4pnI8fC2q2aJd/WH1o8jnknlTTv1H8fanPk2OBzDp6F8ViI80ae39Fo5stTjQe3ZUm09/33CVNK0q8SSrS4Jkqk3HT0nFm/srzPCpl7qxeGSRm7N5HWBaIcCWKbMof3CUOVSb+xq4KaYBEIWTbNryAghut9KXbMiArhet6YW8QRIk2ySnJO+Me76BgxBnNzFrZ6Hv+tR/bmvJ+chhjTnOqfaBshuMa0zXF4g2bjmh5QS+jJXIgTT4/aUgWs4/c9LG7q6U5nY5TKuHjaOLSDM+pAwfpV8="
    - secure: "GoK9dJWoiyO8n5L/wViuek9wDnWDxFqPA+BzqqJQjI03e2Lrlp7tZLFZzH+CmRG5QvHQTS0AAhaGsHwO4kiyCINEuYT2XMi5Umpgyp8X4ZRv5AA7I+55+UN7metswsw/wL7H3/l7bOBXjCmEtjt5LhdY59SwE+xwRPtMuU0CFXfzinF9gfwC2bapQFJkYzcv7Ud2nLFB1GoGEQW8rm2Xa7WNTPBsdh3vhsa7aPjVffsfW00TlkIxyqUn1/kicSu45HHTMG+e/MnO3n6mdGCU9HaexaMiFAOA+0jPCGy0c1s6sCjvMYv50yEGKIp+MhZFK7vOexQ7J6+IwLy86SYCTfpDuiob8+7U3vXltT5J6crc7z0Vm08rR54w3Qr4xTb+A2FjZNLvVUvAgssWHdDOX6RpxLCftU6a7STBHO1jHYSe7/3QNfNTfkYGpqyUkSxLDEHSXiKQYsJivd7i16vNVkfphXaimOCL1cGLXBTpRWEhW3wmYmm8vkALqVhDHyNwTvEfa8dzOZzEWGF7WPGw3oClfFmR94/i9bIckmzDD4WwX2BXemSGhgteaWSpW1xOoPHrzGizRf7g3tbFROIhbYqmo2Fz0MRs2fbbNeE+JHc2dArNNyU8s7C3+3RyFUZM+7ec51DBK7A0GusQOsVytmW/z3O2WW2DEmmq1X8PGQ4="
    - secure: "VrV9J49cRu+w/xDAlgaYe5BPLX1sJKwxluwLgZe0NdI8NAyco8KCcgDhVDIh/4cmWSxTf5OTOLJqyfFMT/owThPBLmCT1cSdw9hsl45hnWz2VXCBpVs258Wk+fKbfhWysawDopJqeKNHIYlkXkQqZChWEoRdKRyRUHJnEOlA4mGtOG5BUJPxgH/oRZZrYsXjnWJFpjIfeRQ0BQ0b4mzUlv6YceV+ZMR5MPyDMFVkiTQEJ+nhTOV+1SWJshWTtnqQWas9qjcj/m6G7m0xmRKFeL8oUMnDPOVBE9Rb7kpacFdGgvOcDMnvjKr/EbYU+kccgnA/mQY1OD5NXrMf3b/FrOcL7R18sZnUl221W6XaTC6r2rH7TrJBKW2YbHa24yBhaekR2fyZnj2+JEDQQNvnvKimEokyE7TdQoiLbKJ3v7hOTF65z04XQmCm4jXOtah3RANOhkXfPST1g9aSRHiWWtBi9zxIhWjmhRa9InFEKNCfpHUZAEVANRp2YOtlddjOIxPGOCdmNUOdWnVcmtu63KxSsmd5ep1SYMnaPlftslaLvTg5BjrrZJ6fFy2EREIRzIXX3MypJNyKXMXwI/B0c/J65x42N05NK40TYmh1yQOj+XgL7tojY4N5GynWmYA29TzTdoyewwig0eclR2PfjWJi3aJyzqRFJ5MB9AbyFI8="

jobs:
  include:
  - os: linux
    arch: amd64
    script:
    - wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
    - sudo apt-get update
    - sudo apt-get install -y VirtualBox-7.0
    - vboxmanage -v
    - wget -q https://download.virtualbox.org/virtualbox/7.0.26/Oracle_VM_VirtualBox_Extension_Pack-7.0.26-168464.vbox-extpack
    - echo 'y\n' | sudo vboxmanage extpack install Oracle_VM_VirtualBox_Extension_Pack-7.0.26-168464.vbox-extpack

  - os: linux
    arch: arm64
    script:
    - echo "TBA"

  # https://docs.travis-ci.com/user/reference/osx/#macos-version
  - os: macos
    osx_image: xcode14.2 # macOS 12.6
    arch: amd64
    script:
    - wget -q -O VMware-Fusion-13.6.2-24409261_universal.dmg "https://www.googleapis.com/drive/v3/files/1EUj2WznX-ifhPF2iJx9lmod-3mU5d6_7?alt=media&key=${GDRIVE_API_KEY}"
    - md5 VMware-Fusion-13.6.2-24409261_universal.dmg
    - hdiutil attach VMware-Fusion-13.6.2-24409261_universal.dmg
    - sudo cp -R /Volumes/VMware\ Fusion/VMware\ Fusion.app /Applications

  - os: macos
    osx_image: xcode14.2 # macOS 12.6
    arch: arm64
    script:
    - wget -q -O VMware-Fusion-13.6.2-24409261_universal.dmg "https://www.googleapis.com/drive/v3/files/1EUj2WznX-ifhPF2iJx9lmod-3mU5d6_7?alt=media&key=${GDRIVE_API_KEY}"
    - md5 VMware-Fusion-13.6.2-24409261_universal.dmg
    - hdiutil attach VMware-Fusion-13.6.2-24409261_universal.dmg
    - sudo cp -R /Volumes/VMware\ Fusion/VMware\ Fusion.app /Applications


install: true
