name: Build Docker Boxes

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  PRODUCT_VERSION: "latest"

permissions:
  contents: read
  packages: write

jobs:
  # build *.fusion.pkr.hcl for amd64 + arm64
  docker-aarch64:
    strategy:
      matrix:
        images:
        - alpine
        - distroless-debian
    runs-on: ubuntu-24.04-arm # preview + required public repo
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # https://github.com/hashicorp/setup-packer
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Initialize Packer and validate HCLs
        working-directory: ${{ matrix.images }}
        run: |
          packer init .

      - name: Build Boxes with Packer
        working-directory: ${{ matrix.images }}
        env:
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
          HCP_CLIENT_ID: ${{ secrets.PACKER_HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.PACKER_HCP_CLIENT_SECRET }}
          VAGRANT_HCP_CLIENT_ID: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
          VAGRANT_HCP_CLIENT_SECRET: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          packer validate .
          PACKER_LOG=1 packer build -only docker.${{ matrix.images }}_arm64 .

  # docker-x86-64:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     # https://github.com/hashicorp/setup-packer
  #     - name: Setup packer
  #       uses: hashicorp/setup-packer@main
  #       with:
  #         version: ${{ env.PRODUCT_VERSION }}

  #     - name: Initialize Packer and validate HCLs
  #       working-directory: ${{ matrix.images }}
  #       run: |
  #         packer init .

  #     - name: Build Boxes with Packer
  #       working-directory: ${{ matrix.images }}
  #       env:
  #         HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  #         HCP_CLIENT_ID: ${{ secrets.PACKER_HCP_CLIENT_ID }}
  #         HCP_CLIENT_SECRET: ${{ secrets.PACKER_HCP_CLIENT_SECRET }}
  #         VAGRANT_HCP_CLIENT_ID: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
  #         VAGRANT_HCP_CLIENT_SECRET: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
  #         GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         packer validate .
  #         PACKER_LOG=1 packer build -only docker.${{ matrix.images }}_amd64 .
