name: Build VirtualBox Boxes

on:
  # push:
  #   branches:
  #     - 'main'
  pull_request:
  workflow_dispatch:

env:
  PRODUCT_VERSION: "latest"

jobs:
  # build *.vbox.pkr.hcl for amd64 + arm64
  vbox-aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install VirtualBox
        run: |
          brew install virtualbox
          wget -q https://download.virtualbox.org/virtualbox/7.1.8/Oracle_VirtualBox_Extension_Pack-7.1.8-168469.vbox-extpack
          ls -al

      - name: Install extensions
        run: |
          echo 'y\n' | sudo vboxmanage extpack install Oracle_VirtualBox_Extension_Pack-7.1.8-168469.vbox-extpack

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      # For debug
      - name: Test buildings with packer
        # env:
        #   VAGRANT_HCP_CLIENT_ID: ${{ secrets.VAGRANT_HCP_CLIENT_ID }}
        #   VAGRANT_HCP_CLIENT_SECRET: ${{ secrets.VAGRANT_HCP_CLIENT_SECRET }}
        #   GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd alpine/
          packer init .
          echo ""
          echo ""
          packer validate .
          echo ""
          echo ""
          PACKER_LOG=1 sudo -E packer build -only virtualbox-iso.alpine_arm64 .
          # PACKER_LOG=1 \
          # VAGRANT_HCP_CLIENT_ID=${{ secrets.VAGRANT_HCP_CLIENT_ID }} \
          # VAGRANT_HCP_CLIENT_SECRET=${{ secrets.VAGRANT_HCP_CLIENT_SECRET }} \
          # GHCR_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          # PACKER_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          # sudo packer build -only virtualbox-iso.alpine_arm64 .


  vbox-x86_64:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
